version: '3.4'

services:
  postgres:
    image: postgres:alpine
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "secret"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
  pgbouncer:
    image: pgbouncer/pgbouncer
    ports: 
      - "5439:5439"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASES_HOST: "postgres"
      DATABASES_PORT: "5432"
      DATABASES_USER: "postgres"
      DATABASES_PASSWORD: "secret"
      DATABASES_DBNAME: "url_shortener"
      PGBOUNCER_LISTEN_PORT: "5439"
  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"
  urlshortener.webapi:
    build:
      context: .
      dockerfile: UrlShortener.WebApi/Dockerfile
    depends_on:
      - "pgbouncer"
      - "redis"
    environment:
      ConnectionStrings__Master: "Host=postgres;Port=5432;Database=url_shortener;Username=postgres;Password=secret;"
      ConnectionStrings__Default: "Host=pgbouncer;Port=5439;Database=url_shortener;Username=postgres;Password=secret;Pooling=false"
      Redis__Hosts__0__Host: "redis"
      Redis__Hosts__0__Port: "6379"